// Generated by CoffeeScript 1.12.4
var Type, isType, type;

isType = require("isType");

Type = require("Type");

type = Type("Logger_Line");

type.defineArgs(function() {
  return {
    create: function(args) {
      if (isType(args[0], Number)) {
        args[0] = {
          index: args[0]
        };
      }
      return args;
    },
    types: {
      index: Number,
      contents: String
    },
    defaults: {
      contents: ""
    },
    required: {
      index: true
    }
  };
});

type.defineValues(function(options) {
  return {
    index: options.index,
    contents: options.contents,
    length: options.contents.length
  };
});

module.exports = type.build();
